# Generated by Django 5.2.6 on 2025-09-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_announcement'),
    ]

    operations = [
    ]
